### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by fepegar** [soxofaan/dahuffman#25]
Hi and thanks a lot for sharing this very nice package, with which I'm playing at
- https://github.com/fepegar/jvol/pull/15

My CI uses Python 3.12 and I've noticed that `pkg_resources` is gone, so an error is raised at codecs/__init__.py

[This is the migration guide](https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename), but unless I'm missing something, which I probably am, `pkg_resources` is not needed in this package and using `__file__` would be enough to load the pickled codecs.

I'm happy to contribute with a PR with your guidance.

**Comment by fepegar** [comment]
I see that this has been fixed in 5b7d7cfe98710cfe9ad0dc41f6b52b07c46d6a57. However, there are no recent releases. Any plans for a new PyPI version?

**Comment by fepegar** [comment]
Related to
- https://github.com/soxofaan/dahuffman/issues/19
- https://github.com/soxofaan/dahuffman/issues/23

**Comment by soxofaan** [comment]
thanks for reporting

good point that the latest release on pypi is pretty old :smile:   
I'll try to push a release somewhere this weekend

**Comment by soxofaan** [comment]
0.4.2 should be available now on pypi

**Comment by fepegar** [comment]
Thank you!
