### ISSUE TITLE
Make _EOF optional in Huffman codec

### ISSUE THREAD

**Issue by DanielGerl** [soxofaan/dahuffman#9]
For my purpose, I do not need the End-of-File character to appear in the tree. I therefore suggest to add a parameter to `HuffmanCodec.from_frequencies()` which allows to disable the insertion of _EOF into the tree.

I would change line 181, 186 and 194 as seen in `huffmancodec.py` attached.
[huffmancodec.zip](https://github.com/soxofaan/dahuffman/files/4686253/huffmancodec.zip)

**Comment by soxofaan** [comment]
Hi Daniel, thanks for your interest.

Do you mean to suppress the EOF symbol in the code table print? Or you want to skip it altogether in all processing? Note that it is necessary if you encode to bytes so you can properly mark the end of the bit stream (which not necessarily aligns with the byte boundaries).

**Comment by DanielGerl** [comment]
The idea is to skip it altogether and therefore not add it to the heap in the first place.

I currently work with ZIP compression which uses the Huffman algorithm to encode an alphabet consisting of 288 literals. This alphabet already contains an EOF character.

**Comment by soxofaan** [comment]
I added an argument to `from_frequencies` so you can now provide your own EOF symbol
https://github.com/soxofaan/dahuffman/blob/7bbc964cee6947545ee4dfb4456c96c9be44cebc/dahuffman/huffmancodec.py#L248-L253

does that cover your use case @DanielGerl ?

**Comment by DanielGerl** [comment]
Thanks for the change! That works fine for me.
